### ISSUE TITLE
No such file or directory: 'N/A/pipeline/pipeline_english_nuig.tsv.pkl'

### ISSUE THREAD

**Issue by kernc** [acdh-oeaw/elexis-mwsa-service#1]
I get an error while launching swagger_server:
```
$ python -m swagger_server

[nltk_data] Downloading package wordnet to /home/user/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.2.2.json: 139kB [00:00, 16.9MB/s]                                                                                                                                                                                               
2021-07-15 16:00:19 INFO: Downloading default packages for language: sl (Slovenian)...
2021-07-15 16:00:20 INFO: File exists: /home/user/stanza_resources/sl/default.zip.
2021-07-15 16:00:22 INFO: Finished downloading models and saved to /home/user/stanza_resources.
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.2.2.json: 139kB [00:00, 18.2MB/s]                                                                                                                                                                                               
2021-07-15 16:00:22 INFO: Downloading default packages for language: sr (Serbian)...
2021-07-15 16:00:23 INFO: File exists: /home/user/stanza_resources/sr/default.zip.
2021-07-15 16:00:28 INFO: Finished downloading models and saved to /home/user/stanza_resources.
2021-07-15 16:00:28.865521: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-07-15 16:00:28.865558: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
DEBUG:connexion.app:Root Path: /home/user/git/elexis-mwsa-service/swagger_server
DEBUG:connexion.app:Specification directory: /home/user/git/elexis-mwsa-service/swagger_server/swagger
DEBUG:connexion.app:Setting error handlers
DEBUG:connexion.apis.abstract:Loading specification: /home/user/git/elexis-mwsa-service/swagger_server/swagger/swagger.yaml
DEBUG:openapi_spec_validator.decorators:Attaching x-scope to {'$ref': '#/components/schemas/DefinitionPair'}
DEBUG:openapi_spec_validator.decorators:Attaching x-scope to {'$ref': '#/components/schemas/Features'}
DEBUG:openapi_spec_validator.decorators:Attaching x-scope to {'$ref': '#/components/schemas/Feature'}
DEBUG:openapi_spec_validator.decorators:Attaching x-scope to {'$ref': '#/components/schemas/ScoreInput'}
DEBUG:openapi_spec_validator.decorators:Attaching x-scope to {'$ref': '#/components/schemas/DefinitionPair'}
DEBUG:openapi_spec_validator.decorators:Attaching x-scope to {'$ref': '#/components/schemas/Scores'}
DEBUG:openapi_spec_validator.decorators:Attaching x-scope to {'$ref': '#/components/schemas/DefinitionPair', 'x-scope': ['', '#/components/schemas/ScoreInput']}
DEBUG:openapi_spec_validator.decorators:Ref #/components/schemas/DefinitionPair already has scope attached
DEBUG:openapi_spec_validator.decorators:Attaching x-scope to {'$ref': '#/components/schemas/Feature', 'x-scope': ['', '#/components/schemas/Features']}
DEBUG:openapi_spec_validator.decorators:Ref #/components/schemas/Feature already has scope attached
DEBUG:openapi_spec_validator.validators:Dereferencing {'/acdh-mwsa': {'get': {'summary': 'readiness check', 'operationId': 'acdh_mwsa_get', 'responses': {'200': {'description': 'ready'}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}}, '/acdh-mwsa/features': {'post': {'summary': 'Extract features for given definition pair', 'operationId': 'acdh_mwsa_features_post', 'requestBody': {'content': {'applciation/json': {'schema': {'$ref': '#/components/schemas/DefinitionPair', 'x-scope': ['']}}}}, 'responses': {'201': {'description': 'Created', 'content': {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Features', 'x-scope': ['']}, 'x-content-type': 'application/json'}}}}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}, '/achda-mwsa/scores/': {'post': {'summary': 'Get word sense alignment of definition pairs', 'operationId': 'achda_mwsa_scores_post', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ScoreInput', 'x-scope': ['']}}}}, 'responses': {'201': {'description': 'Created', 'content': {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Scores', 'x-scope': ['']}, 'x-content-type': 'application/json'}}}}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'get': {'summary': 'readiness check', 'operationId': 'acdh_mwsa_get', 'responses': {'200': {'description': 'ready'}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'get': {'summary': 'readiness check', 'operationId': 'acdh_mwsa_get', 'responses': {'200': {'description': 'ready'}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'summary': 'readiness check', 'operationId': 'acdh_mwsa_get', 'responses': {'200': {'description': 'ready'}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}
DEBUG:openapi_spec_validator.validators:Dereferencing {'post': {'summary': 'Extract features for given definition pair', 'operationId': 'acdh_mwsa_features_post', 'requestBody': {'content': {'applciation/json': {'schema': {'$ref': '#/components/schemas/DefinitionPair', 'x-scope': ['']}}}}, 'responses': {'201': {'description': 'Created', 'content': {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Features', 'x-scope': ['']}, 'x-content-type': 'application/json'}}}}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}
DEBUG:openapi_spec_validator.validators:Dereferencing {'post': {'summary': 'Extract features for given definition pair', 'operationId': 'acdh_mwsa_features_post', 'requestBody': {'content': {'applciation/json': {'schema': {'$ref': '#/components/schemas/DefinitionPair', 'x-scope': ['']}}}}, 'responses': {'201': {'description': 'Created', 'content': {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Features', 'x-scope': ['']}, 'x-content-type': 'application/json'}}}}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}
DEBUG:openapi_spec_validator.validators:Dereferencing {'summary': 'Extract features for given definition pair', 'operationId': 'acdh_mwsa_features_post', 'requestBody': {'content': {'applciation/json': {'schema': {'$ref': '#/components/schemas/DefinitionPair', 'x-scope': ['']}}}}, 'responses': {'201': {'description': 'Created', 'content': {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Features', 'x-scope': ['']}, 'x-content-type': 'application/json'}}}}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}
DEBUG:openapi_spec_validator.validators:Dereferencing {'post': {'summary': 'Get word sense alignment of definition pairs', 'operationId': 'achda_mwsa_scores_post', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ScoreInput', 'x-scope': ['']}}}}, 'responses': {'201': {'description': 'Created', 'content': {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Scores', 'x-scope': ['']}, 'x-content-type': 'application/json'}}}}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'post': {'summary': 'Get word sense alignment of definition pairs', 'operationId': 'achda_mwsa_scores_post', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ScoreInput', 'x-scope': ['']}}}}, 'responses': {'201': {'description': 'Created', 'content': {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Scores', 'x-scope': ['']}, 'x-content-type': 'application/json'}}}}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'summary': 'Get word sense alignment of definition pairs', 'operationId': 'achda_mwsa_scores_post', 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ScoreInput', 'x-scope': ['']}}}}, 'responses': {'201': {'description': 'Created', 'content': {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Scores', 'x-scope': ['']}, 'x-content-type': 'application/json'}}}}}, 'x-openapi-router-controller': 'swagger_server.controllers.default_controller'}
DEBUG:openapi_spec_validator.validators:Dereferencing {'schemas': {'ScoreInput': {'required': ['classifier', 'pair'], 'properties': {'classifier': {'type': 'string', 'description': "classifier to use for alignment. 'randomforest' or 'bert'", 'example': 'randomforst'}, 'pair': {'$ref': '#/components/schemas/DefinitionPair', 'x-scope': ['', '#/components/schemas/ScoreInput']}}}, 'Scores': {'required': ['alignment', 'probability'], 'type': 'object', 'properties': {'alignment': {'type': 'string', 'description': "alignment of definition pair. 'exact', 'related', 'broader', 'narrower', 'none'", 'example': 'narrower'}, 'probability': {'type': 'number', 'description': 'probability of the pairs for the alignment', 'format': 'float', 'example': 0.8}}, 'example': {'probability': 0.8, 'alignment': 'narrower'}}, 'Features': {'required': ['features', 'headword', 'pos'], 'type': 'object', 'properties': {'headword': {'type': 'string', 'description': 'headword of the definition pair', 'example': 'olive'}, 'pos': {'type': 'string', 'description': 'Part-of-speech of the headword'}, 'features': {'type': 'array', 'items': {'$ref': '#/components/schemas/Feature', 'x-scope': ['', '#/components/schemas/Features']}}}, 'example': {'features': [{'name': 'jaccard', 'value': 0.9}, {'name': 'jaccard', 'value': 0.9}], 'headword': 'olive', 'pos': 'pos'}}, 'Feature': {'required': ['name', 'value'], 'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'name of the feature', 'example': 'jaccard'}, 'value': {'type': 'number', 'description': 'value of the feature', 'format': 'float', 'example': 0.9}}, 'example': {'name': 'jaccard', 'value': 0.9}}, 'DefinitionPair': {'required': ['def1', 'def2', 'headword', 'lang'], 'type': 'object', 'properties': {'headword': {'type': 'string', 'description': 'headword of the definition pair', 'example': 'olive'}, 'pos': {'type': 'string', 'description': 'Part-of-speech of the headword', 'example': 'noun'}, 'lang': {'type': 'string', 'description': 'ISO 639-1 language code of the definition pair', 'example': 'en'}, 'def1': {'type': 'string', 'description': 'first of the definition pair', 'example': 'a small green or black Mediterranean fruit, eaten or used to make oil'}, 'def2': {'type': 'string', 'description': 'second of the definition pair', 'example': 'a type of edible fruit which is used as a garnish etc and which gives oil used for cooking'}}}}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'ScoreInput': {'required': ['classifier', 'pair'], 'properties': {'classifier': {'type': 'string', 'description': "classifier to use for alignment. 'randomforest' or 'bert'", 'example': 'randomforst'}, 'pair': {'$ref': '#/components/schemas/DefinitionPair', 'x-scope': ['', '#/components/schemas/ScoreInput']}}}, 'Scores': {'required': ['alignment', 'probability'], 'type': 'object', 'properties': {'alignment': {'type': 'string', 'description': "alignment of definition pair. 'exact', 'related', 'broader', 'narrower', 'none'", 'example': 'narrower'}, 'probability': {'type': 'number', 'description': 'probability of the pairs for the alignment', 'format': 'float', 'example': 0.8}}, 'example': {'probability': 0.8, 'alignment': 'narrower'}}, 'Features': {'required': ['features', 'headword', 'pos'], 'type': 'object', 'properties': {'headword': {'type': 'string', 'description': 'headword of the definition pair', 'example': 'olive'}, 'pos': {'type': 'string', 'description': 'Part-of-speech of the headword'}, 'features': {'type': 'array', 'items': {'$ref': '#/components/schemas/Feature', 'x-scope': ['', '#/components/schemas/Features']}}}, 'example': {'features': [{'name': 'jaccard', 'value': 0.9}, {'name': 'jaccard', 'value': 0.9}], 'headword': 'olive', 'pos': 'pos'}}, 'Feature': {'required': ['name', 'value'], 'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'name of the feature', 'example': 'jaccard'}, 'value': {'type': 'number', 'description': 'value of the feature', 'format': 'float', 'example': 0.9}}, 'example': {'name': 'jaccard', 'value': 0.9}}, 'DefinitionPair': {'required': ['def1', 'def2', 'headword', 'lang'], 'type': 'object', 'properties': {'headword': {'type': 'string', 'description': 'headword of the definition pair', 'example': 'olive'}, 'pos': {'type': 'string', 'description': 'Part-of-speech of the headword', 'example': 'noun'}, 'lang': {'type': 'string', 'description': 'ISO 639-1 language code of the definition pair', 'example': 'en'}, 'def1': {'type': 'string', 'description': 'first of the definition pair', 'example': 'a small green or black Mediterranean fruit, eaten or used to make oil'}, 'def2': {'type': 'string', 'description': 'second of the definition pair', 'example': 'a type of edible fruit which is used as a garnish etc and which gives oil used for cooking'}}}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'required': ['classifier', 'pair'], 'properties': {'classifier': {'type': 'string', 'description': "classifier to use for alignment. 'randomforest' or 'bert'", 'example': 'randomforst'}, 'pair': {'$ref': '#/components/schemas/DefinitionPair', 'x-scope': ['', '#/components/schemas/ScoreInput']}}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'required': ['alignment', 'probability'], 'type': 'object', 'properties': {'alignment': {'type': 'string', 'description': "alignment of definition pair. 'exact', 'related', 'broader', 'narrower', 'none'", 'example': 'narrower'}, 'probability': {'type': 'number', 'description': 'probability of the pairs for the alignment', 'format': 'float', 'example': 0.8}}, 'example': {'probability': 0.8, 'alignment': 'narrower'}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'required': ['features', 'headword', 'pos'], 'type': 'object', 'properties': {'headword': {'type': 'string', 'description': 'headword of the definition pair', 'example': 'olive'}, 'pos': {'type': 'string', 'description': 'Part-of-speech of the headword'}, 'features': {'type': 'array', 'items': {'$ref': '#/components/schemas/Feature', 'x-scope': ['', '#/components/schemas/Features']}}}, 'example': {'features': [{'name': 'jaccard', 'value': 0.9}, {'name': 'jaccard', 'value': 0.9}], 'headword': 'olive', 'pos': 'pos'}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'required': ['name', 'value'], 'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'name of the feature', 'example': 'jaccard'}, 'value': {'type': 'number', 'description': 'value of the feature', 'format': 'float', 'example': 0.9}}, 'example': {'name': 'jaccard', 'value': 0.9}}
DEBUG:openapi_spec_validator.validators:Dereferencing {'required': ['def1', 'def2', 'headword', 'lang'], 'type': 'object', 'properties': {'headword': {'type': 'string', 'description': 'headword of the definition pair', 'example': 'olive'}, 'pos': {'type': 'string', 'description': 'Part-of-speech of the headword', 'example': 'noun'}, 'lang': {'type': 'string', 'description': 'ISO 639-1 language code of the definition pair', 'example': 'en'}, 'def1': {'type': 'string', 'description': 'first of the definition pair', 'example': 'a small green or black Mediterranean fruit, eaten or used to make oil'}, 'def2': {'type': 'string', 'description': 'second of the definition pair', 'example': 'a type of edible fruit which is used as a garnish etc and which gives oil used for cooking'}}}
DEBUG:connexion.apis.abstract:Read specification
DEBUG:connexion.apis.abstract:Options Loaded
DEBUG:connexion.apis.flask_api:Creating API blueprint: /ACDH/ACDH_MWSA_Service/1o
DEBUG:connexion.apis.abstract:Security Definitions: {}
DEBUG:connexion.apis.abstract:Validate Responses: False
DEBUG:connexion.apis.abstract:Strict Request Validation: False
DEBUG:connexion.apis.abstract:Pythonic params: True
DEBUG:connexion.apis.abstract:pass_context_arg_name: None
DEBUG:connexion.apis.flask_api:Adding spec json: /ACDH/ACDH_MWSA_Service/1o//openapi.json
DEBUG:connexion.apis.flask_api:Adding spec yaml: /ACDH/ACDH_MWSA_Service/1o//openapi.yaml
DEBUG:connexion.apis.flask_api:Adding swagger-ui: /ACDH/ACDH_MWSA_Service/1o/ui/
DEBUG:connexion.apis.abstract:Adding /ACDH/ACDH_MWSA_Service/1o/acdh-mwsa...
DEBUG:connexion.operations.openapi3:consumes: ['application/json']
DEBUG:connexion.operations.openapi3:produces: ['application/json']
DEBUG:connexion.apis.flask_api:... Adding GET -> swagger_server.controllers.default_controller.acdh_mwsa_get
DEBUG:connexion.operations.abstract:... Produces: ['application/json']
DEBUG:connexion.operations.abstract:... Produces json
DEBUG:connexion.operations.abstract:... Adding produces decorator (<function AbstractOperation.__content_type_decorator.<locals>.<lambda> at 0x7f0858005840>)
DEBUG:connexion.operations.secure:... Security: None
DEBUG:connexion.operations.abstract:... Adding security decorator (<function security_passthrough at 0x7f090c3161e0>)
DEBUG:connexion.apis.abstract:Adding /ACDH/ACDH_MWSA_Service/1o/acdh-mwsa/features...
DEBUG:connexion.operations.openapi3:consumes: ['applciation/json']
DEBUG:connexion.operations.openapi3:produces: ['application/json']
DEBUG:connexion.apis.flask_api:... Adding POST -> swagger_server.controllers.default_controller.acdh_mwsa_features_post
DEBUG:connexion.operations.abstract:... Produces: ['application/json']
DEBUG:connexion.operations.abstract:... Produces json
DEBUG:connexion.operations.abstract:... Adding produces decorator (<function AbstractOperation.__content_type_decorator.<locals>.<lambda> at 0x7f085803e158>)
DEBUG:connexion.operations.secure:... Security: None
DEBUG:connexion.operations.abstract:... Adding security decorator (<function security_passthrough at 0x7f090c3161e0>)
DEBUG:connexion.apis.abstract:Adding /ACDH/ACDH_MWSA_Service/1o/achda-mwsa/scores/...
DEBUG:connexion.operations.openapi3:consumes: ['application/json']
DEBUG:connexion.operations.openapi3:produces: ['application/json']
DEBUG:connexion.apis.flask_api:... Adding POST -> swagger_server.controllers.default_controller.achda_mwsa_scores_post
DEBUG:connexion.operations.abstract:... Produces: ['application/json']
DEBUG:connexion.operations.abstract:... Produces json
DEBUG:connexion.operations.abstract:... Adding produces decorator (<function AbstractOperation.__content_type_decorator.<locals>.<lambda> at 0x7f085803e510>)
DEBUG:connexion.operations.secure:... Security: None
DEBUG:connexion.operations.abstract:... Adding security decorator (<function security_passthrough at 0x7f090c3161e0>)
INFO:swagger_server.services.service:loading english model

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/git/elexis-mwsa-service/swagger_server/__main__.py", line 40, in <module>
    main()
  File "/home/user/git/elexis-mwsa-service/swagger_server/__main__.py", line 35, in main
    FlaskInjector(app=app.app, modules=[configure])
  File "/home/user/git/dictionary-matrix/venv/lib/python3.7/site-packages/flask_injector/__init__.py", line 316, in __init__
    injector.binder.install(module)
  File "/home/user/git/dictionary-matrix/venv/lib/python3.7/site-packages/injector/__init__.py", line 577, in install
    instance(self)
  File "/home/user/git/elexis-mwsa-service/swagger_server/__main__.py", line 28, in configure
    AlignmentScoringService()
  File "/home/user/git/elexis-mwsa-service/swagger_server/services/service.py", line 77, in __init__
    self.model = ModelService() if not lang_model else lang_model
  File "/home/user/git/elexis-mwsa-service/swagger_server/services/service.py", line 122, in __init__
    with open(en_pipeline_path, 'rb') as en_file:
FileNotFoundError: [Errno 2] No such file or directory: 'N/A/pipeline/pipeline_english_nuig.tsv.pkl'
```

I see there is [_pipeline/pipeline_english_nuig.tsv.pkl **.dvc**_ in the repo](https://github.com/acdh-oeaw/elexis-mwsa-service/tree/master/models/pipeline). I also notice:
```sh
$ grep . **/config.yaml
config.yaml:default:
config.yaml:  model_path: ${MODEL_PATH}
swagger_server/config.yaml:default:
swagger_server/config.yaml:  model_path: ${MODEL_PATH}
swagger_server/services/config.yaml:default:
swagger_server/services/config.yaml:  model_path: ${MODEL_PATH}
```
What do I set `$MODEL_PATH` to?

Is there any insight into the above error you can share?

**Comment by sbyim** [comment]
Hi,
The description in the README was a bit outdated, I've updated the description to use docker image.
